name: Build Docker Images

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        # mavros
        docker build docker/mavros --tag mavros:melodic-ros-base
        # fleet-beacon
        docker build . --tag fleet-beacon:$(date +%s)
